<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="YADHU" failures="1" tests="2" name="testRunner.MyRunnerTest" time="17.008" errors="0" timestamp="2025-10-02T11:26:21 CEST" skipped="0">
  <testcase classname="testRunner.MyRunnerTest" name="runScenario" time="7.614"/>
  <testcase classname="testRunner.MyRunnerTest" name="runScenario" time="9.394">
    <failure message="expected [4] but found [2]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: expected [4] but found [2]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1590)
at org.testng.Assert.assertEqualsImpl(Assert.java:150)
at org.testng.Assert.assertEquals(Assert.java:132)
at org.testng.Assert.assertEquals(Assert.java:1431)
at org.testng.Assert.assertEquals(Assert.java:1395)
at org.testng.Assert.assertEquals(Assert.java:1441)
at stepDefinitions.HomeAndCart.check_if_quatity_of_the_product_is_added_and_verify_total_price(HomeAndCart.java:63)
at âœ½.Check if "4" quantity of the product is added(file:///C:/Users/yadhu/eclipse-workspace/MyTest/GreenKart/src/test/resources/FeatureFiles/validate_shoping.feature:27)
]]>
    </failure>
  </testcase> <!-- runScenario -->
</testsuite> <!-- testRunner.MyRunnerTest -->
